vich_uploader:
    db_driver: orm
    metadata : 
        type: attribute    

    mappings:
       recipes:
           uri_prefix: /images/recipes
           upload_destination: '%kernel.project_dir%/public/images/recipes'
